name: "Check Formatting"
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: lint
        uses: gradle/gradle-build-action@v2
      - run: gradle spotlessCheck